# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Itee-Plugin-Three CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MOZ_HEADLESS: 1
    strategy:
      matrix:
        node-version: [ 20.x, 22.x, 24.x ]
        firefox: [ 'latest' ]
    steps:
      - name: Checkout ${{ env.GITHUB_REPOSITORY }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Firefox ${{ matrix.firefox }}
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: ${{ matrix.firefox }}
      - name: Install dependencies
        run: npm clean-install
      - name: Build package
        run: npm run build
      - name: Check code linting
        run: npm run lint
      - name: Tests
        run: npm run tests:run

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ env.GITHUB_REPOSITORY }}
        uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm clean-install
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Pre-Release
        run: npm run clean && npm run lint && npm run doc && npm run build
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
